#!/usr/bin/env python

from argparse import ArgumentParser

parser = ArgumentParser(usage="%(prog)s [args] cutflow1.p cutflow2.p ...")
#parser.add_argument('-i',"--import", dest="imports",
#                  help="path to module required to unpickle cutflows", default=None)
parser.add_argument('files', nargs="+")
args = parser.parse_args()

"""
if args.imports is not None:
    import os
    import imp
    for path in args.imports.split(','):
        name = os.path.splitext(os.path.basename(path))[0]
        imp.load_source(name, path)
"""

import sys
from rootpy.tree.filtering import FilterList
try:
    import cPickle as pickle
except:
    import pickle

event_filters = []
object_filters = []

for p in args.files:
    f = open(p)
    d = pickle.load(f)
    event_filters.append(d["event"])
    object_filters.append(d["object"])
    f.close()

totalEventFilter = reduce(FilterList.merge, event_filters)
totalObjectFilter = reduce(FilterList.merge, object_filters)

pfile = open("cutflow.p", 'w')
pickle.dump({"event": totalEventFilter,
             "object": totalObjectFilter}, pfile)
pfile.close()

print "Event Filters:"
print totalEventFilter

print "Object Filters:"
print totalObjectFilter
