#!/usr/bin/env python

import sys
from rootpy.tree.filtering import FilterList
try:
    import cPickle as pickle
except:
    import pickle

event_filters = []
object_filters = []

for p in sys.argv[1:]:
    f = open(p)
    d = pickle.load(f)
    event_filters.append(d["event"])
    object_filters.append(d["object"])
    f.close()

totalEventFilter = reduce(FilterList.merge, event_filters)
totalObjectFilter = reduce(FilterList.merge, object_filters)

pfile = open("cutflow.p", 'w')
pickle.dump({"event": totalEventFilter,
             "object": totalObjectFilter}, pfile)
pfile.close()

print "Event Filters:"
print totalEventFilter

print "Object Filters:"
print totalObjectFilter
