#!/usr/bin/env python

from argparse import ArgumentParser

parser = ArgumentParser(usage="%(prog)s [args] cutflow1.p cutflow2.p ...")
parser.add_argument('-i',"--import", type=str, dest="importmod",
                  help="path to module required to unpickle cutflows", default=None)
parser.add_argument('files', type=str, nargs="+")
args = parser.parse_args()

if args.importmod is not None:
    import os
    name = os.path.splitext(os.path.basename(args.importmod))[0]
    import imp
    imp.load_source(name, args.importmod)

import sys
from rootpy.tree.filtering import FilterList
try:
    import cPickle as pickle
except:
    import pickle

event_filters = []
object_filters = []

for p in args.files:
    f = open(p)
    d = pickle.load(f)
    event_filters.append(d["event"])
    object_filters.append(d["object"])
    f.close()

totalEventFilter = reduce(FilterList.merge, event_filters)
totalObjectFilter = reduce(FilterList.merge, object_filters)

pfile = open("cutflow.p", 'w')
pickle.dump({"event": totalEventFilter,
             "object": totalObjectFilter}, pfile)
pfile.close()

print "Event Filters:"
print totalEventFilter

print "Object Filters:"
print totalObjectFilter
