#!/usr/bin/env python

from argparse import ArgumentParser

parser = ArgumentParser(usage="%(prog)s [args] samplename1 samplename2 ...")
parser.add_argument('-m',"--meta", type=str, dest="metadata",
                  help="", default="datasets.yml")
parser.add_argument("--version", type=int, dest="version",
                  help="version number appended to output dataset name", default=1)
parser.add_argument("--extFile", type=str, dest="extfile",
                  help="extra files to send to worker nodes", default=None)
parser.add_argument('-s',"--student", type=str, dest="student",
                  help="the file (excluding .py extension) containing a class of the same name inheriting from rootpy.batch.Student", default=None)
parser.add_argument('-u',"--user", type=str, dest="user",
                  help="your grid dataset username i.e. JohnDoe", required=True)
parser.add_argument("--nosite", action='store_true',
                  help="override site in metadata and let the grid decide")
parser.add_argument('datasets', type=str, nargs="+")
args, user_args = parser.parse_known_args()

import yaml
import sys
from subprocess import call
import fnmatch

metafile = open(args.metadata)
metadata = yaml.load(metafile)
metafile.close()

sorted_datasets = sorted(metadata.keys())

# expand globs
datasets = []
for dataset in args.datasets:
    if '*' in dataset:
        datasets += fnmatch.filter(sorted_datasets, dataset)
    else:
        datasets.append(dataset)

for dataset in datasets:
    if not dataset in metadata:
        sys.exit("dataset %s not defined in metadata %s" % (dataset, args.metadata))
    inDS = metadata[dataset]["container"]
    if not type(inDS) is list:
        inDS = [inDS]
    for panda_inDS in inDS:
        panda_site = None
        if ':' in panda_inDS:
            panda_inDS, panda_site = panda_inDS.split(':') 
        panda_bexec = "setup.sh"
        panda_exec = "source setup.sh; grid-batch --dataset %s --metadata %s --student %s %%IN" % (dataset, args.metadata, args.student)
        panda_outDS = "user.%s.%s.%s.v%i" % (args.user, args.student, dataset, args.version)
        panda_outputs = "%s.root,cutflow.p" % dataset 
        panda_extFiles = "*.so"
        if not args.extfile is None:
            panda_extFiles = ",".join([panda_extFiles, args.extfile])
        panda_opts = ["--excludeFile .git", "--extFile %s" % panda_extFiles] # "--nGBPerJob 8"
        command = [
            "prun",
            "--bexec \"%s\"" % panda_bexec,
            "--exec \"%s\"" % panda_exec,
            "--inDS %s" % panda_inDS,
            "--outDS %s" % panda_outDS,
            "--outputs %s" % panda_outputs
        ] + panda_opts
        if not panda_site is None and "--site" not in user_args and not args.nosite:
            command.append("--site %s" % panda_site)
        command = " ".join(command)
        if user_args:
            command += " %s" % user_args
        print "executing:"
        print command
        call(command, shell=True)
