#!/usr/bin/env python

from optparse import OptionParser

parser = OptionParser()
options, args = parser.parse_args()

import re
import os
import glob
import shutil

tarfiles = []
for arg in args:
    tarfiles += glob.glob(os.path.join(arg,"*XYZ.tgz"))

pattern = "^user.(?P<name>\w+).(?P<jobid>[0-9]+).(?P<LFN>\w+).(?P<suffix>.+)$"

for filename in tarfiles:
    match = re.match(pattern, os.path.basename(filename))
    if not match:
        print "%s not a valid filename"% filename
        continue
    outdir = "user.%s.%s"% (match.group('name'), match.group('LFN'))
    if not os.path.exists(outdir):
        os.mkdir(outdir)
    if os.path.isfile(outdir):
        print "a file at %s already exists!"% outdir
        continue
    dest = os.path.join(outdir, os.path.basename(filename))
    if os.path.exists(dest):
        print "duplicate file: %s"% filename
        continue
    shutil.move(filename, dest)
