#!/usr/bin/env python

from goodruns.extern.argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('-o', '--output', required=True)
parser.add_argument('-i', '--inputs', default=None)
parser.add_argument('files', nargs='*')
args = parser.parse_args()

from subprocess import call
import sys

if args.inputs is not None:
    args.inputs = args.inputs.split(',')
else:
    args.inputs = args.files

if args.output.endswith('.root'):
    # standard ROOT merge
    call('hadd %s %s' % (args.output, ' '.join(args.inputs)), shell=True)
elif args.output.endswith('.p'):
    # merge cutflow pickles
    try:
        import cPickle as pickle
    except ImportError:
        import pickle
    from rootpy.tree.filtering import Filter, FilterList
    event_filter_lists = []
    object_filter_lists = []
    for input in args.inputs:
        with open(input) as p:
            d = pickle.load(p)
            event_filter_lists.append(d['event'])
            object_filter_lists.append(d['object'])
    event_filter_list = reduce(FilterList.merge, event_filter_lists)
    print event_filter_list
    object_filter_list = reduce(FilterList.merge, object_filter_lists)
    print object_filter_list
    with open(args.output, 'w') as output:
        pickle.dump({'event': event_filter_list,
                     'object': object_filter_list}, output)
else:
    sys.exit("unsupported file type")
