#!/usr/bin/env python

import sys
from atlastools import environment
from argparse import ArgumentParser
from subprocess import call

parser = ArgumentParser(usage="%(prog)s [options] command")
parser.add_argument("--env","-e",type=str,dest="env",default="",help="the name of the environment")
args, user_args = parser.parse_known_args()

if args.env != "":
    status = environment.load(args.env)
    if not status:
        sys.exit(1)

if len(user_args) == 1:
    user_args = user_args[0].split()

call(user_args)
