#!/usr/bin/env python

import sys, os
from optparse import OptionParser

parser = OptionParser()
(options, args) = parser.parse_args()

import ROOT

if not os.environ.has_key('DATAROOT'):
    print 'Warning: $DATAROOT not defined!'
    dataroot = None
dataroot = os.environ['DATAROOT']

if dataroot:
    for filename in args:
        datafile = ROOT.TFile(filename, "update")
        if not datafile:
            sys.exit("could not open %s"% filename)
        print "updating metadata in %s..."% filename
        for metafile in ['variables.yml','datasets.yml','trees.yml']:
            globalxml = os.path.join(dataroot,metafile)
            if os.path.isfile(globalxml):
                print "embedding %s..."%globalxml
                xml = open(globalxml,'r')
                content = "\n".join(xml.readlines())
                xml.close()
                named = ROOT.TNamed(metafile,content)
                named.Write("", ROOT.TObject.kOverwrite)
        datafile.Close()
